services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 6eujF6tR
      MYSQL_USER: the-network-backend
      MYSQL_PASSWORD: 6eujF6tR3s2
      MYSQL_DATABASE: the-network
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    platform: linux/x86_64
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
